// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eagjtgrzswxqaclxeuom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhZ2p0Z3J6c3d4cWFjbHhldW9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5MTk1MTAsImV4cCI6MjA1MTQ5NTUxMH0.IUTq674oty69ta1NDn-URrm0Y3c1RwV19y_u03xKtEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);